Repository bitcampJavaProj/JavaToDoList, pull requests merged in 2024-02, with the labels that each got.

#1 투두리스트 DTO, DAO 작성 및 기능 구현
  JavaToDoList/src/DAO/TeamToDoListDAO.java
  JavaToDoList/src/DTO/TeamToDoList.java
Labels: feat

#10 Feature/todo list read
  JavaToDoList/.classpath
  JavaToDoList/lib/json-20240205.jar
  JavaToDoList/src/DAO/TeamTodoListDAO.java
  JavaToDoList/src/DAO/TeamTodoListRecord.java
  JavaToDoList/src/DTO/TeamTodoList.java
  JavaToDoList/src/mysql/DBConnection.java
Labels: feat

#11 투두리스트 클래스 수정
  JavaToDoList/src/DTO/TeamToDoList.java
Labels: fix

#12 투두리스트 코드 충돌 해결
  JavaToDoList/src/DAO/TeamToDoListDAO.java
  JavaToDoList/src/DAO/TeamTodoListRecord.java
  JavaToDoList/src/DTO/TeamToDoList.java
  JavaToDoList/src/DTO/TeamTodoList.java
  JavaToDoList/src/client/Client.java
  JavaToDoList/src/server/Server.java
Labels: fix

#13 feat : TeamToDoList toString 수정 + 잡다한 수정
  JavaToDoList/src/DAO/TeamToDoListDAO.java
  JavaToDoList/src/DTO/SortByDate.java
  JavaToDoList/src/DTO/TeamToDoList.java
  JavaToDoList/src/server/Server.java
Labels: fix

#15 메뉴 인터페이스 구현
  JavaToDoList/src/DAO/TeamToDoListDAO.java
  JavaToDoList/src/client/ServiceMenu.java
Labels: feat

#16 메뉴 인터페이스 수정
  JavaToDoList/src/client/ServiceMenu.java
Labels: fix

#17 서버 및 클라이언트에 회원가입, 로그인 기능 구현
  JavaToDoList/src/client/Client.java
  JavaToDoList/src/server/Server.java
Labels: feat

#18 feat : TeamToDoListDao.getTodoList 기능 구현 #5
  JavaToDoList/src/DAO/TeamToDoListDAO.java
Labels: feat

#19 Update README.md
  README.md
Labels: fix

#21 불필요한 클래스 삭제 및 클래스명 수정
  JavaToDoList/src/DAO/ChoiceDAO.java
  JavaToDoList/src/DAO/DiaryDAO.java
  JavaToDoList/src/DAO/QuestionDAO.java
  JavaToDoList/src/DAO/UserToTeamDAO.java
  JavaToDoList/src/DTO/Choice.java
  JavaToDoList/src/DTO/Diary.java
  JavaToDoList/src/DTO/Question.java
  JavaToDoList/src/DTO/UserToTeam.java
  JavaToDoList/src/server/Server.java
Labels: fix, delete

#27 투두리스트클래스, DAO 수정
  JavaToDoList/src/DAO/ToDoListDAO.java
  JavaToDoList/src/DTO/ToDoList.java
Labels: fix

#29 Fix/client code fixed
  JavaToDoList/src/client/Client.java
Labels: fix

#30 feat : Diary 클래스 생성, gettersetter 추가
  JavaToDoList/src/DTO/Diary.java
Labels: feat

#33 feat : 일기 제목, 내용 수정 기능 추가
  JavaToDoList/src/DAO/DiaryDAO.java
Labels: feat

#36 fix: user class fixed
  JavaToDoList/src/DTO/User.java
Labels: fix

#37 fix / UserDAO fixed
  JavaToDoList/src/DAO/UserDAO.java
Labels: fix

#38 feat : login feature
  JavaToDoList/src/DAO/LoginDAO.java
  JavaToDoList/src/DAO/ToDoListDAO.java
  JavaToDoList/src/DAO/UserDAO.java
  JavaToDoList/src/DTO/SortByDate.java
  JavaToDoList/src/server/Server.java
Labels: feat

#45 서버 코드 구축 및 수정
  JavaToDoList/src/DTO/Cmd.java
  JavaToDoList/src/server/Server.java
Labels: fix

#46 Update README.md
  README.md
Labels: fix

#47 서버 코드 수정
  JavaToDoList/src/server/Server.java
Labels: fix

#48 fix: 투두리스트DAO 메소드 static으로 변환
  JavaToDoList/src/DAO/ToDoListDAO.java
Labels: fix

#49 del: loginDAO 삭제
  JavaToDoList/src/DAO/LoginDAO.java
Labels: delete

#50 fix. DiaryDAO method static 변경, Diary 생성자 수정
  JavaToDoList/src/DAO/DiaryDAO.java
  JavaToDoList/src/DTO/Diary.java
Labels: fix

#51 fix: Client 코드 구축(handleSignUp 메소드 참고하기)
  JavaToDoList/src/client/Client.java
Labels: fix

#52 Cmd, User 클래스 수정
  JavaToDoList/src/DTO/Cmd.java
  JavaToDoList/src/DTO/User.java
Labels: fix

#55 fix: ToDoList 생성자 추가
  JavaToDoList/src/DTO/ToDoList.java
Labels: fix

#62 feat : 클라이언트에서 일기 작성 기능 추가
  JavaToDoList/src/DAO/DiaryDAO.java
  JavaToDoList/src/DTO/Diary.java
  JavaToDoList/src/client/Client.java
Labels: feat, fix

#64 feat: server, client에 todolist 작성 기능 구현
  JavaToDoList/src/DAO/ToDoListDAO.java
  JavaToDoList/src/DTO/ToDoList.java
  JavaToDoList/src/client/Client.java
Labels: feat

#70 feat: 투두리스트DAO 수정 및 클라이언트에 투두리스트 삭제 기능 구현
  JavaToDoList/src/DAO/ToDoListDAO.java
  JavaToDoList/src/client/Client.java
  JavaToDoList/src/server/Server.java
Labels: feat, fix

#72 fix: 투두리스트 작성 값 입력 수정
  JavaToDoList/src/client/Client.java
Labels: fix

#79 feat: 투두리스트 수정 기능 구현 및 코드 전반 수정
  JavaToDoList/src/DAO/ToDoListDAO.java
  JavaToDoList/src/DTO/ToDoList.java
  JavaToDoList/src/client/Client.java
  JavaToDoList/src/server/Server.java
Labels: feat, fix

#82 feat : 일기 삭제 기능 추가 (서버, 클라이언트 적용)
  JavaToDoList/src/DAO/DiaryDAO.java
  JavaToDoList/src/DTO/Diary.java
  JavaToDoList/src/client/Client.java
  JavaToDoList/src/server/Server.java
Labels: feat, fix

#83 feat : client todolist read fix
  JavaToDoList/src/DAO/ToDoListDAO.java
  JavaToDoList/src/DAO/UserDAO.java
  JavaToDoList/src/client/Client.java
Labels: feat, fix

#84 fix/todolistupdate 코드 수정
  JavaToDoList/src/client/Client.java
Labels: fix

#85 fix : 다이어리 수정 안 되던 오류 수정
  JavaToDoList/src/DAO/DiaryDAO.java
  JavaToDoList/src/client/Client.java
Labels: bug, fix

#86 fix : Client.java logout fix + add interface logout
  JavaToDoList/src/client/Client.java
  JavaToDoList/src/client/ServiceMenu2.java
Labels: fix

#87 fix : client 입력받는 부분 수정
  JavaToDoList/src/client/Client.java
Labels: bug, fix

#88 fix/client, server 로그아웃 수정
  JavaToDoList/src/client/Client.java
  JavaToDoList/src/server/Server.java
Labels: fix

#91 fix/코드 전반 수정
  JavaToDoList/src/DAO/DiaryDAO.java
  JavaToDoList/src/DAO/UserDAO.java
  JavaToDoList/src/DTO/Diary.java
  JavaToDoList/src/client/Client.java
  JavaToDoList/src/server/Server.java
Labels: fix

#92 fix : 주석, 설명 추가
  JavaToDoList/src/DTO/Diary.java
  JavaToDoList/src/client/Client.java
Labels: delete

#93 fix/클라이언트 투두리스트 break문 추가
  JavaToDoList/src/client/Client.java
Labels: fix

#95 fix/user 기능 수정
  JavaToDoList/src/client/Client.java
Labels: fix
